project/models.py
from project import db

class Todo(db.Model):
    __tablename__ = 'todos'

    id = db.Column(db.Integer, primary_key=True)
    msg = db.Column(db.String(250), index=False, unique=False)
    done = db.Column(db.Boolean, index=False, unique=False, default=False)

    def __repr__(self):
        return '<todo {}>'.format(self.msg)

project/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, SubmitField
from wtforms.validators import DataRequired


class AddForm(FlaskForm):
    msg = StringField('Message', validators=[DataRequired()])
    done = BooleanField('Done', default=False)
    submit = SubmitField('Add')

project/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy


app = Flask(__name__)
app.config['SECRET_KEY'] = 'soSecretThatEvenVoldemortIsScaredToSayIt'

POSTGRES = {
    'user': 'postgres',
    'pw': 'qwerty',
    'db': 'todo',
    'host': 'localhost',
    'port': '5432',
}
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://%(user)s:%(pw)s@%(host)s:%(port)s/%(db)s' % POSTGRES

db = SQLAlchemy(app)
migrate = Migrate(app, db)

from project.home.views import home_blueprint
app.register_blueprint(home_blueprint)

from project.api.views import api_blueprint
app.register_blueprint(api_blueprint)

project/api/views.py
from flask import Blueprint, request
from flask.views import MethodView
from flask import jsonify

from project.models import Todo
from project import db

api_blueprint = Blueprint('api', __name__)


class TodoAPI(MethodView):

    def get(self):
        cols = ['id', 'msg', 'done']
        data = Todo.query.all()
        result = [{col: getattr(d, col) for col in cols} for d in data]
        return jsonify(result)

    def post(self):
        msg = request.values.get('msg', None)
        if msg:
            todo = Todo()
            todo.msg = msg
            todo.done = bool(request.values.get('done', False))
            db.session.add(todo)
            db.session.commit()
            return 'OK'
        else:
            return 'No msg in request params :-('


api_blueprint.add_url_rule('/api/', view_func=TodoAPI.as_view('api'))

project/home/views.py
from flask import render_template, Blueprint, redirect, url_for
from project.models import Todo
from .forms import AddForm
from project import db


# CONFIG
home_blueprint = Blueprint('home', __name__, template_folder='templates')


@home_blueprint.route('/')
@home_blueprint.route('/index')
def index():
    user = {'username': 'Piotrek'}

    # todos = [
    #     {
    #         'id': 0,
    #         'msg': 'przygotuj sie na pylight',
    #         'done': False
    #     },
    #     {
    #         'id': 1,
    #         'msg': 'Opierdzielaj sie ogladajac anime liczac na to ze uda Ci sie przygotowac prezentacja w locie',
    #         'done': True
    #     }
    # ]

    todos = Todo.query.all()

    return render_template('index.html', title='TODO', user=user, todos=todos)

@home_blueprint.route('/add_todo', methods=['GET', 'POST'])
@home_blueprint.route('/edit_todo/<id>', methods=['GET', 'POST'])
def add_todo(id=None):
    todo = Todo.query.get(id) if id is not None else Todo()
    form = AddForm(obj=todo)

    if form.validate_on_submit():
        form.populate_obj(todo)
        db.session.add(todo)
        db.session.commit()
        return redirect(url_for('home.index'))

    return render_template('add.html', title='Add new todo', form=form)

project/templates/add.html
{% extends "base.html" %}

{% block content %}
<h1>Add yet another todo</h1>
<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.msg.label }}
        {{ form.msg(size=250, class='form-control') }}
        {% for error in form.msg.errors %}
            <small id="msgError" class="form-text text-danger">{{ error }}</small>
        {% endfor %}
    </div>
    <div class="form-group form-check">
        {{ form.done(class_='form-check-input') }}
        {{ form.done.label }}
    </div>
    {{ form.submit(class_='btn btn-primary') }}
</form>
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <title>{{ title }} - TODO</title>
    </head>
    <body style="">
        <nav class="navbar navbar-light bg-light">
          <a class="navbar-brand" href="{{ url_for('home.index') }}">
            TODO's
          </a>
          <a class="navbar-brand" href="{{ url_for('home.add_todo') }}">
            ADD
          </a>
        </nav>
        <hr>
        {% block content %}{% endblock %}

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

project/templates/index.html
{% extends "base.html" %}

{% block content %}
<ul class="list-group">
    {% for todo in todos %}
    <li class="list-group-item d-flex justify-content-between align-items-center {% if todo.done %} list-group-item-success {% else %} list-group-item-danger {% endif %}">
        {{ todo.msg }}
        <a href="/edit_todo/{{ todo.id }}"><span class="badge badge-primary badge-pill">EDIT</span></a>
    </li>
    {% endfor %}
    </ul>
{% endblock %}